import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import json

# Configuration
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, 'Data')
DOCS_DIR = os.path.join(BASE_DIR, 'Docs')
IMAGES_DIR = os.path.join(BASE_DIR, 'Images')

INPUT_FILE = os.path.join(BASE_DIR, 'Files', 'TotalResult_Labeled.csv')
REPORT_FILE = os.path.join(DOCS_DIR, 'Analysis_Report.md')
PARAM_FILE = os.path.join(DATA_DIR, 'initial_params.json')

# Analysis Period
START_DATE = '2026-01-01'
END_DATE = '2026-02-11'

def load_and_filter_data():
    if not os.path.exists(INPUT_FILE):
        raise FileNotFoundError(f"{INPUT_FILE} NOT FOUND.")
    
    print(f"Loading {INPUT_FILE}...")
    df = pd.read_csv(INPUT_FILE)
    
    # CLEANUP: Strip whitespace from column names
    df.columns = df.columns.str.strip()
    print("Columns found:", df.columns.tolist())
    
    df['Time'] = pd.to_datetime(df['Time'])
    
    # Filter by date
    mask = (df['Time'] >= START_DATE) & (df['Time'] <= END_DATE)
    df_filtered = df.loc[mask].copy()
    
    print(f"Filtered Data ({START_DATE} ~ {END_DATE}): {len(df_filtered)} rows")
    return df_filtered

def analyze_correlations(df):
    print("Analyzing correlations...")
    
    # Define Label Columns
    labels = ['Label_Open_Buy', 'Label_Open_Sell', 'Label_Close_Buy', 'Label_Close_Sell']
    
    # Identify Indicator Columns (excluding Time, OHLC, Labels)
    exclude_cols = ['Time', 'Open', 'High', 'Low', 'Close'] + labels
    feature_cols = [c for c in df.columns if c not in exclude_cols]
    
    # Check for Dual LRA columns (Logic check)
    lra_cols = [c for c in feature_cols if 'LRA' in c]
    print(f"LRA Features found: {lra_cols}")
    
    # Calculate Correlation Matrix
    corr_matrix = df[feature_cols + labels].corr(method='pearson')
    
    # Extract correlations with Labels
    label_corrs = corr_matrix[labels].loc[feature_cols]
    
    return label_corrs

def generate_report(label_corrs, df):
    print("Generating report...")
    if not os.path.exists(DOCS_DIR):
        os.makedirs(DOCS_DIR)
        
    with open(REPORT_FILE, 'w', encoding='utf-8') as f:
        f.write("# Data Analysis Report\n\n")
        f.write(f"**Analysis Period**: {START_DATE} ~ {END_DATE}\n")
        f.write(f"**Data Count**: {len(df)} rows\n\n")
        
        f.write("## 1. Feature-Label Correlations\n")
        f.write("Top 10 Positive/Negative Correlations for Label_Open_Buy:\n\n")
        
        # Sort by Buy Label
        buy_corr = label_corrs['Label_Open_Buy'].sort_values(ascending=False)
        f.write("### Positive Correlation (Buy Signal)\n")
        f.write(buy_corr.head(10).to_markdown() + "\n\n")
        f.write("### Negative Correlation (Buy Signal)\n")
        f.write(buy_corr.tail(10).to_markdown() + "\n\n")
        
        f.write("## 2. Dual LRAVGSTD Analysis\n")
        lra_cols = [c for c in df.columns if 'LRA' in c]
        if lra_cols:
            lra_corr = label_corrs.loc[lra_cols]
            f.write(lra_corr.to_markdown() + "\n\n")
            f.write("> **Insight**: Compare sensitivity of Short (60) vs Long (180) periods.\n\n")
            
        f.write("## 3. Intra-Indicator Relationships\n")
        # BOP Example
        bop_cols = [c for c in df.columns if 'BOP' in c]
        if bop_cols:
             f.write("### BOP Group\n")
             f.write(label_corrs.loc[bop_cols].to_markdown() + "\n\n")
             
    print(f"Report saved to {REPORT_FILE}")

def suggest_initial_params(label_corrs):
    # This is a heuristic placeholder. 
    # Real logic would infer "best starting ranges" based on feature importance.
    # For now, we pass the generic ranges defined in task to the Optimizer, 
    # or specific 'best guess' if we had a way to map feature values to parameters.
    
    # Creating a dummy structure for Optimizer to consume
    params = {
        "notes": "Generated by Data_Analyst",
        "suggested_focus": "Based on high correlation features"
    }
    
    with open(PARAM_FILE, 'w') as f:
        json.dump(params, f, indent=4)
    print(f"Initial params saved to {PARAM_FILE}")

def main():
    try:
        df = load_and_filter_data()
        corrs = analyze_correlations(df)
        generate_report(corrs, df)
        suggest_initial_params(corrs)
        print("Done.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
